-- Watchit veritabanının başlangıç şeması.
-- Flyway'e geçilen gün (5 Ekim 2026) çalışan veritabanından pg_dump ile çıkarıldı.
-- Kural adları (uk..., fk...) Hibernate'in ürettiği adlarla birebir aynı bırakıldı;
-- böylece eski veritabanı ile sıfırdan kurulan veritabanı aynı adları taşır.
-- BU DOSYA ARTIK DEĞİŞTİRİLMEZ. Yeni bir değişiklik için V2__... dosyası açılır.

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    email      varchar(255) NOT NULL,
    password   varchar(255),
    username   varchar(255),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

CREATE TABLE channels (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_image_url    varchar(255),
    channel_name        varchar(255),
    created_at          timestamp(6) NOT NULL,
    description         varchar(255),
    handle              varchar(255) NOT NULL,
    profile_picture_url varchar(255),
    subscriber_count    bigint,
    total_views         bigint,
    verified            boolean,
    video_count         bigint,
    owner_id            bigint,
    CONSTRAINT ukor1qklmmrhv4bxvhgnb2akdll UNIQUE (handle),
    CONSTRAINT fkc6sorav30ddgywp6vt99wen6x FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE videos (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          timestamp(6) NOT NULL,
    description         varchar(255),
    duration_in_seconds integer,
    thumbnail_url       varchar(255),
    title               varchar(255),
    video_url           varchar(255),
    category            bigint,
    channel_id          bigint,
    CONSTRAINT fk32o7ys79vui9rcl07cdktdfg7 FOREIGN KEY (category) REFERENCES categories (id),
    CONSTRAINT fkbaube8rnq6coeqb22rt2fv8hh FOREIGN KEY (channel_id) REFERENCES channels (id)
);

CREATE TABLE comments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content           varchar(1000) NOT NULL,
    created_at        timestamp(6) NOT NULL,
    edited            boolean NOT NULL,
    like_count        bigint,
    updated_at        timestamp(6) NOT NULL,
    parent_comment_id bigint,
    user_id           bigint,
    video_id          bigint,
    CONSTRAINT fk7h839m3lkvhbyv3bcdv7sm4fj FOREIGN KEY (parent_comment_id) REFERENCES comments (id),
    CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fkesqgvcfwlscgco0dqkdnvw8l3 FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE TABLE comment_likes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    comment_id bigint,
    user_id    bigint,
    CONSTRAINT ukgu1pee3567af29uutdfy0fcjd UNIQUE (user_id, comment_id),
    CONSTRAINT fk3wa5u7bs1p1o9hmavtgdgk1go FOREIGN KEY (comment_id) REFERENCES comments (id),
    CONSTRAINT fk6h3lbneryl5pyb9ykaju7werx FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE video_likes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    user_id    bigint,
    video_id   bigint,
    CONSTRAINT uk5tlc8gm2hqk6pd2ef02jhmx9b UNIQUE (user_id, video_id),
    CONSTRAINT fk8gal6orxcks0llsblhsc8yxu7 FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fkh5xdmkusmdp62bin35eulq2ny FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE TABLE subscriptions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id    bigint,
    subscriber_id bigint,
    CONSTRAINT ukcl91bj6bsg2kvi3eity8yc4hk UNIQUE (subscriber_id, channel_id),
    CONSTRAINT fkdf2ga5low0yg96racryj3alkc FOREIGN KEY (channel_id) REFERENCES channels (id),
    CONSTRAINT fkoodc4352epkjrvxx79odlxbji FOREIGN KEY (subscriber_id) REFERENCES users (id)
);

CREATE TABLE playlists (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) NOT NULL,
    description varchar(255),
    is_public   boolean,
    title       varchar(255),
    updated_at  timestamp(6) NOT NULL,
    owner_id    bigint,
    CONSTRAINT fkn0r1rrm19f8j7wfl656bd9sus FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE playlist_videos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) NOT NULL,
    order_index integer,
    updated_at  timestamp(6) NOT NULL,
    playlist_id bigint,
    video_id    bigint,
    CONSTRAINT uk3ex8uu6wos3w18w1df8ruapgw UNIQUE (playlist_id, video_id),
    CONSTRAINT fk9k328sk1nnj1oihl99w8w0nuw FOREIGN KEY (playlist_id) REFERENCES playlists (id),
    CONSTRAINT fkagtsknljsxw3o4bsmt6svs18l FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE TABLE notifications (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) NOT NULL,
    is_read     boolean,
    message     varchar(255),
    title       varchar(255),
    type        varchar(255),
    receiver_id bigint,
    sender_id   bigint,
    CONSTRAINT notifications_type_check CHECK (type IN ('LIKE', 'COMMENT', 'SUBSCRIBE', 'VIDEO_UPLOAD')),
    CONSTRAINT fk13vcnq3ukas06ho1yrbc5lrb5 FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk9kxl0whvhifo6gw4tjq36v53k FOREIGN KEY (receiver_id) REFERENCES users (id)
);

CREATE TABLE watch_history_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) NOT NULL,
    is_completed    boolean,
    last_watched_at timestamp(6) NOT NULL,
    watched_seconds integer,
    user_id         bigint,
    video_id        bigint,
    CONSTRAINT uk8p7pkrbfr39elgkncrvm4jxjx UNIQUE (user_id, video_id),
    CONSTRAINT fkdv2gmwgbah9oic0gfp0ugdge FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fkqkle8cmswdq5k364lgf5feyr3 FOREIGN KEY (video_id) REFERENCES videos (id)
);
